### ISSUE TITLE
Aproveitamento de celulas

### ISSUE THREAD

**Issue by baptvit** [lhfranca/Analise_Dados#1]
1. Tenta aproveitar mais as celulas no jupyter notebook assim vc evita ter que execultar uma celula muito grande para vizualiar um resultado.

* Uma celula com descrição de import de dados

`df=pd.read_csv("def_area_2004_2019.csv")
df_fire= pd.read_csv("inpe_brazilian_amazon_fires_1999_2019.csv")
df.head(10)`

* Segue as outras celulas com descrições melhores

2. Sempre importa tudo no topo do arquivo com os imports primeitos depois os from * imports 
`sns.set_style('whitegrid')
from matplotlib.pyplot import MaxNLocator, FuncFormatter`

**Comment by lhfranca** [comment]
1. Nesse caso, o ideal seria fazer em uma linha? Sem dar enter para a próxima?
2. Essa parte foi a que encontrei em um projeto no Kaggle, reparei isso também, vou dar uma editada depois.

**Comment by baptvit** [comment]
1. O ideal é separar em blocos de celulas do jupyter.

**Comment by lhfranca** [comment]
Agora sim entendi, pode crer.
