### ISSUE TITLE
Trocando o número do mês pelo nome, tem como fazer de outro jeito?

### ISSUE THREAD

**Issue by baptvit** [lhfranca/Analise_Dados#2]
Vê se isso ajuda, sei que vai ser em inglês

https://docs.python.org/3/library/calendar.html#calendar.month_abbr

```
import calendar

for month_idx in range(1, 13):
    print (calendar.month_name[month_idx])
    print (calendar.month_abbr[month_idx])
    print ("")

```

```

import calendar

from moth_num in range(1,13):
   df_fire.month.replace(moth_num, calendar.month_abbr[moth_num], inplace=True)

```

**Comment by lhfranca** [comment]
Legal, realmente o resultado fica em inglês, mas usa menos linhas pelo menos.
Na segunda parte estava dando erro, ai mudei para 'for' ao invés de 'from'.
Dica boa demais, acho que vou manter desse jeito que está, só porque quero em português (se existir um jeito de traduzir será legal). Mas mesmo assim, para projetos futuros será muito útil, vlww!
